# Generated by Django 6.1 on 2026-08-16 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('subjects', '0002_alter_subject_options_alter_topic_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'topic'], name='questions_q_subject_c4fa34_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty_level'], name='questions_q_difficu_2e0825_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by'], name='questions_q_created_078554_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_global', 'status', 'is_active'], name='questions_q_is_glob_1ee36d_idx'),
        ),
    ]
