# Generated by Django 6.1 on 2026-08-28 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_options_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductedExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('question_order', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='teachers.conductedexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_exam_questions', to='questions.question')),
            ],
            options={
                'ordering': ['question_order'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'question'), name='unique_question_per_conducted_exam'), models.UniqueConstraint(fields=('exam', 'question_order'), name='unique_question_order_per_conducted_exam')],
            },
        ),
    ]
