# Generated by Django 6.1 on 2026-08-28 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_conductedexamquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductedExamParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('ongoing', 'Ongoing'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted')], default='joined', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='teachers.conductedexam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='conducted_exam_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['exam', 'status'], name='teachers_co_exam_id_43d40e_idx'), models.Index(fields=['student', 'status'], name='teachers_co_student_1df5fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam', 'student'), name='unique_student_per_conducted_exam')],
            },
        ),
    ]
