# Generated by Django 6.1 on 2026-08-28 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_conductedexamparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductedExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='teachers.conductedexamquestion')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='teachers.conductedexamparticipant')),
            ],
            options={
                'indexes': [models.Index(fields=['participant', 'exam_question'], name='teachers_co_partici_ffa815_idx')],
                'constraints': [models.UniqueConstraint(fields=('participant', 'exam_question'), name='unique_answer_per_participant_question')],
            },
        ),
    ]
