# Generated by Django 6.1 on 2026-08-23 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_examattempt_examanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Blur'), ('fullscreen_exit', 'Fullscreen Exit'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('right_click', 'Right Click'), ('idle', 'Idle'), ('rapid_answer', 'Rapid Answer')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exams.examattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['attempt'], name='security_ex_attempt_6addf9_idx'), models.Index(fields=['event_type'], name='security_ex_event_t_fe63f7_idx')],
            },
        ),
    ]
