# Generated by Django 6.1 on 2026-08-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        ('teachers', '0004_conductedexamanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductedExamSecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Blur'), ('fullscreen_exit', 'Fullscreen Exit'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('right_click', 'Right Click'), ('minimize_attempt', 'Minimize Attempt'), ('keyboard_attempt', 'Keyboard Attempt')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='teachers.conductedexamparticipant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['participant', 'timestamp'], name='security_co_partici_2f5b17_idx'), models.Index(fields=['event_type'], name='security_co_event_t_d06fa8_idx')],
            },
        ),
    ]
